### ISSUE TITLE
整理訪問者特質（一共六個）

### ISSUE THREAD

**Issue by noxs315** [CYCU-UX-foundation/Team-6#24]
大家把自己訪問對象的個人特質打到miro上後面方便persona的整理
一共有六個受訪者

**Comment by noxs315** [comment]
記得要把背景也補充下去，包含受訪者使用ilearning的時長，大幾，任教多少年等等。

**Comment by xuanyi12345** [comment]
我寫了兩個一個是紅蘿蔔 一個是理工科老師
